spring:
  application:
    name: 07-Cloud-Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ErSusant/Configuration_Properties
          
server:
  port: 9093
